# Generated by Django 3.2.13 on 2022-06-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
