# Generated by Django 3.2.13 on 2022-06-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0002_auto_20220618_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_number',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='identifier',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
