# Generated by Django 3.2.13 on 2022-06-19 01:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0003_auto_20220619_0024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('unix_time', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('amt', models.CharField(max_length=255)),
                ('is_fraud', models.BooleanField(default=False)),
                ('merchant', models.CharField(max_length=255)),
                ('merch_lat', models.FloatField(default=0)),
                ('merch_long', models.FloatField(default=0)),
                ('environment', models.CharField(max_length=255)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_processor.customer')),
            ],
        ),
    ]
