# Generated by Django 3.2.13 on 2022-06-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0004_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='model',
            new_name='customer',
        ),
    ]
