# Generated by Django 3.2.13 on 2022-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_processor', '0005_rename_model_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='environment',
            field=models.CharField(default='TESTING', max_length=255),
        ),
    ]
