# Generated by Django 3.2.13 on 2022-06-12 17:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('NNW_CLASSIFIER', 'Modelo Red Neuronal para clasificación'), ('SVM_CLASSIFIER', 'Modelo Support Vector Machine para clasificación')], max_length=100)),
                ('enviroment', models.CharField(choices=[('TESTING', 'Testing'), ('PRODUCTION', 'Production'), ('TRAINING', 'Training')], max_length=100)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}')),
                ('architecture_model', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}')),
            ],
            options={
                'verbose_name': 'IAModel',
            },
        ),
        migrations.CreateModel(
            name='IATraining',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUCCEEDED', 'Exitoso'), ('FAILED', 'Fallido')], max_length=100)),
                ('weights', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_models.iamodel')),
            ],
            options={
                'verbose_name': 'IATraining',
            },
        ),
    ]
