# Generated by Django 3.2.13 on 2022-06-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_rename_enviroment_iamodel_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iatraining',
            name='weights',
        ),
        migrations.AddField(
            model_name='iatraining',
            name='weights_url',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
