# Generated by Django 3.2.13 on 2022-06-12 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0003_auto_20220612_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='iatraining',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
