# Generated by Django 3.2.13 on 2022-06-26 00:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0004_iatraining_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='IATrainingResults',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('auc', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('loss', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('val_loss', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('precision', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('recall', models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True)),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_models.iatraining')),
            ],
            options={
                'verbose_name': 'IATrainingResults',
            },
        ),
    ]
